import axiosClient from './axiosClient';

const businessApi = {
  dashboardAdmin: () => axiosClient.get('/dashboard/admin'),
  dashboardStaff: () => axiosClient.get('/dashboard/staff'),
  dashboardClient: () => axiosClient.get('/dashboard/client'),
  staffSchedules: (params) => axiosClient.get('/staff/schedules', { params }),
  staffSchedule: (params) => axiosClient.get('/staff/schedule', { params }),
  staffAppointments: (params) => axiosClient.get('/staff/appointments', { params }),
  staffAttendanceToday: () => axiosClient.get('/staff/attendance/today'),
  staffAttendanceHistory: (params) => axiosClient.get('/staff/attendance/history', { params }),
  staffCheckIn: (payload) => axiosClient.post('/staff/attendance/check-in', payload),
  staffCheckOut: (payload) => axiosClient.post('/staff/attendance/check-out', payload),

  appointments: (params) => axiosClient.get('/appointments', { params }),
  bookAppointment: (payload) => axiosClient.post('/appointments', payload),
  cancelAppointment: (id) => axiosClient.patch(`/appointments/${id}/cancel`),
  checkInAppointment: (id) => axiosClient.post(`/appointments/${id}/check-in`),
  checkOutAppointment: (id) => axiosClient.post(`/appointments/${id}/check-out`),
  startAppointmentService: (id) => axiosClient.patch(`/appointments/${id}/service-start`),
  endAppointmentService: (id) => axiosClient.patch(`/appointments/${id}/service-end`),
  rescheduleAppointment: (id, payload) => axiosClient.put(`/appointments/${id}/reschedule`, payload),
  completeTask: (detailId) => axiosClient.patch(`/appointment-details/${detailId}/complete`),

  myProfile: () => axiosClient.get('/profile/me'),
  updateMyProfile: (payload) => axiosClient.put('/profile/me', payload),
  allergyCatalog: () => axiosClient.get('/allergies'),
  clientHistory: (params) => axiosClient.get('/client/me/history', { params }),
  clientPayments: (params) => axiosClient.get('/client/me/payments', { params }),
  clientPreferences: () => axiosClient.get('/client/me/preferences'),
  updateClientPreferences: (payload) => axiosClient.put('/client/me/preferences', payload),

  feedbackList: (params) => axiosClient.get('/feedback', { params }),
  submitFeedback: (payload) => axiosClient.post('/feedback', payload),
  replyFeedback: (id, payload) => axiosClient.post(`/feedbacks/${id}/reply`, payload),
  replyFeedbackLegacy: (id, payload) => axiosClient.patch(`/feedback/${id}/reply`, payload),
  adminFeedbacks: (params) => axiosClient.get('/admin/feedbacks', { params }),
  staffFeedbacks: (params) => axiosClient.get('/staff/feedbacks', { params }),
  myOrders: (params) => axiosClient.get('/client/me/orders', { params }),
  myOrder: (id) => axiosClient.get(`/client/me/orders/${id}`),
  cancelMyOrder: (id) => axiosClient.patch(`/client/me/orders/${id}/cancel`),
  productCategories: () => axiosClient.get('/products/categories'),
  adminProductCategories: () => axiosClient.get('/admin/product-categories'),
  createAdminProductCategory: (payload) => axiosClient.post('/admin/product-categories', payload),
  updateAdminProductCategory: (id, payload) => axiosClient.put(`/admin/product-categories/${id}`, payload),
  deleteAdminProductCategory: (id) => axiosClient.delete(`/admin/product-categories/${id}`),
  adminServiceCategories: () => axiosClient.get('/admin/service-categories'),
  createAdminServiceCategory: (payload) => axiosClient.post('/admin/service-categories', payload),
  updateAdminServiceCategory: (id, payload) => axiosClient.put(`/admin/service-categories/${id}`, payload),
  deleteAdminServiceCategory: (id) => axiosClient.delete(`/admin/service-categories/${id}`),
  adminAllergies: (params) => axiosClient.get('/admin/allergies', { params }),
  createAdminAllergy: (payload) => axiosClient.post('/admin/allergies', payload),
  updateAdminAllergy: (key, payload) => axiosClient.put(`/admin/allergies/${key}`, payload),
  deleteAdminAllergy: (key) => axiosClient.delete(`/admin/allergies/${key}`),

  services: (params) => axiosClient.get('/management/services', { params }),
  createService: (payload) => axiosClient.post('/management/services', payload),
  updateService: (id, payload) => axiosClient.put(`/management/services/${id}`, payload),
  deleteService: (id) => axiosClient.delete(`/management/services/${id}`),

  promotions: (params) => axiosClient.get('/management/promotions', { params }),
  createPromotion: (payload) => axiosClient.post('/management/promotions', payload),
  updatePromotion: (id, payload) => axiosClient.put(`/management/promotions/${id}`, payload),
  deletePromotion: (id) => axiosClient.delete(`/management/promotions/${id}`),

  products: (params) => axiosClient.get('/management/products', { params }),
  createProduct: (payload) => axiosClient.post('/management/products', payload),
  updateProduct: (id, payload) => axiosClient.put(`/management/products/${id}`, payload),
  deleteProduct: (id) => axiosClient.delete(`/management/products/${id}`),
  adminProducts: (params) => axiosClient.get('/admin/products', { params }),
  adminCreateProduct: (payload) => axiosClient.post('/admin/products', payload),
  adminUpdateProduct: (id, payload) => axiosClient.put(`/admin/products/${id}`, payload),
  adminDeleteProduct: (id) => axiosClient.delete(`/admin/products/${id}`),

  suppliers: (params) => axiosClient.get('/management/suppliers', { params }),
  createSupplier: (payload) => axiosClient.post('/management/suppliers', payload),
  updateSupplier: (id, payload) => axiosClient.put(`/management/suppliers/${id}`, payload),
  deleteSupplier: (id) => axiosClient.delete(`/management/suppliers/${id}`),

  reports: (params) => axiosClient.get('/management/reports', { params }),

  operationsCalendar: (params) => axiosClient.get('/operations/calendar', { params }),
  operationsPerformance: (params) => axiosClient.get('/operations/performance', { params }),
  adminRevenue: (params) => axiosClient.get('/admin/revenue', { params }),

  // Shop checkout (client)
  checkoutCart: (payload) => axiosClient.post('/customer-orders', payload),
  adminOrders: (params) => axiosClient.get('/admin/orders', { params }),
  adminOrderDetail: (id) => axiosClient.get(`/admin/orders/${id}`),
  approveOrder: (id) => axiosClient.put(`/admin/orders/${id}/approve`),
  cancelOrder: (id) => axiosClient.put(`/admin/orders/${id}/cancel`),
  // Admin product orders
  adminProductOrders: (params) => axiosClient.get('/admin/product-orders', { params }),
  adminProductOrderDetail: (id) => axiosClient.get(`/admin/product-orders/${id}`),
  approveProductOrder: (id) => axiosClient.put(`/admin/product-orders/${id}/approve`),
  cancelProductOrder: (id) => axiosClient.put(`/admin/product-orders/${id}/cancel`),
  approveAppointment: (id) => axiosClient.put(`/admin/appointments/${id}/approve`),
  cancelAppointmentAdmin: (id) => axiosClient.put(`/admin/appointments/${id}/cancel`),
  clientNotifications: () => axiosClient.get('/client/notifications'),
  markClientNotificationRead: (id) => axiosClient.put(`/client/notifications/${id}/read`),
};

export default businessApi;
